# fly.toml app configuration file generated for template-project on 2023-10-31T09:29:07+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "template-project"
primary_region = "arn"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
